### PR TITLE
Add Mnemonics to the Zcoin Rich Client

### PR DESCRIPTION
**Pull request by HysMagus**
layout: fr
title: Zcoin Mnemonics Generation and Recovery for Zcoin Client
author: The Arcadia Group
date: January 30, 2020
amount: 638.4
milestones:
  - name: Initial Start of Zcoin Mnemonics Project
    funds: 319.2 (50%)
    done:
    status: unfinished
  - name: Release of Testable Binaries
    funds: 
    done:
    status: unfinished
  - name: Completion and PR of Final Version
    funds: 319.2 (50%)
    done:
    status: unfinished
payouts:
  - date:
    amount:
  - date:
    amount:
---
This proposal is for the integration of Zcoin Mnemonics generation and recovery into the rich client wallet. This covers the following objects: 
* My Mnemonic Recovery Phrase, revealed during initial installation (with 'confirm your recovery phrase' functionality)
* Show My Recovery Phrase button, somewhere in the app
* Re-enter Your Passphrase form, in order to be able to reveal the seed phrase
* My Mnemonic Recovery Phrase screen in-app 

The team for this project is:
* 1 Developer
* 1 UI/UX Designer
* 1 Project Manager

Timeframe:
This project is expected to be completed in 2 weeks but should account for a time frame after completion to get merged into master.

### CODE REVIEW

**Comment by JustSavil** [comment]
This is a great feature to have to make the transition to the rich GUI come further along.

**Comment by reubenyap** [comment]
I would say this is essential. The core team would be donating for a big part of this.

**Comment by BanDoe** [comment]
Mnemonics are a definite must have for the wallet

**Comment by MichaelBernhardt** [comment]
This is badly needed to make the rich GUI wallet even more user friendly. I'll be donating.

**Comment by justanwar** [comment]
Mnemonics will bring the rich GUI wallet up to date with the features in the Core QT wallet.

I look forward to this implementation.

**Comment by liewhuising** [comment]
Recovery phrase is a MUST for zcoin wallet. I just can't wait to see this!

**Comment by ajaydono** [comment]
Much needed feature for the rich GUI. Will be less hassle to recover wallet

**Comment by BanDoe** [comment]
For the future of Zcoin and onwards for its users! Mnemonics is a must for
backup/recovery...

**Comment by reubenyap** [comment]
This project was completed and funded by the core team despite not meeting its full funding goal.

**Pull request merged**
