### PR TITLE
Create explainer video for Zcoin Receiver Address Privacy (RAP)

### PR DESCRIPTION
**Pull request by reubenyap**
Zcoin is set to be the first coin that implements [BIP47 Payment Codes](https://medium.com/@MattoshiN/bip47-reusable-payment-codes-for-hierarchical-deterministic-wallets-fbb0387595ac) in our default wallet or as we call it Receiver Address Privacy.

This allows users to share a single public address without sacrificing privacy and works similarly to Stealth Addresses.

RAP has several advantages in that it can be supported in light wallets and payments to it unlike to Stealth Addresses are indistinguishable from normal payments.

This proposal is to fund a video animation similar to what we have on our Youtube page and the cost of this is roughly 1000 USD which covers voice acting and animation which will highlight the advantages of RAP and what it is.

Estimated time of completion is about 1-2 months.

### CODE REVIEW

**Comment by reubenyap** [comment]
（使用Google翻译翻译）

Zcoin被设置为在我们的默认钱包或我们称为“收件人地址隐私”中实现BIP47付款代码的第一个硬币。

这使用户可以在不牺牲隐私的情况下共享一个公共地址，并且其工作方式与隐形地址类似。

RAP具有多个优点，因为它可以在轻型钱包中使用，并且与Stealth Addresss相比，可以用常规付款方式对其进行区分。

这项提案的目的是资助类似于YouTube网站上的视频动画，其费用约为1000美元，其中包括配音和动画，这将凸显RAP的优点及其实质。

预计完成时间约为1-2个月。

**Comment by HysMagus** [comment]
<s> Awesome stuff! For further reference on why RAP is badass, definitely reference some essential resources when making your quotation such as: </s>

- [BIP47 BIP](https://github.com/bitcoin/bips/blob/master/bip-0047.mediawiki) 
- [Samourai's BIP47 Pitch](https://blog.samouraiwallet.com/post/137698771697/why-were-bringing-reusable-payment-codes-to-the)
I mistakenly thought this was a third party proposal, please ignore my message 😁

**Comment by HysMagus** [comment]
@arcadiamediagroup is down to commit a few XZC if this gets approved

**Comment by Nakamoto-san** [comment]
Would like to contribute to the cost of this

**Comment by vampyren** [comment]
Great proposal.

**Comment by michivollgas** [comment]
we need this video do get the msg out, i would be in for funding!

**Comment by reubenyap** [comment]
This has now been approved and is now open for funding!

**Comment by StreetOps** [comment]
So whu cant i get help fixing this so we dont have to go through this i love to give back. I am solo pool z coin (918) 862-7498 call me tommorow around now or rven now why i hot wifi or ill be sleeping on a pourch at 16th and Denver across from QT big blue house SECOUND house from corner of 15th and denver west side of road ill be the guy in a sleeping bag on porch cause im homeless red backpach and ill be thereas soon as sun goes down they tend to run us off cause everyone hates homeless people and do there best to avoid us. God bless oh i live in tulsa Oklahoma USA thats down town 15th and denver west side of road 2end house front porch homeless guy blue sleeping bag red back pack and probly frezzing unless this thick chick lets me come stay or hit yeaya

**Comment by hexoli** [comment]
Is this video going to be dubbed or subtitled in Portuguese?

**Comment by reubenyap** [comment]
We can do subtitles on Portuguese but will see about dubbing. 




---- On Wed, 15 Jan 2020 22:16:22 +0800 notifications@github.com wrote ----



Is this video going to be dubbed or subtitled in Portuguese?

**Comment by raychieng** [comment]
Good project!

**Comment by raychieng** [comment]
Is the video going to be translated in other languages? Maybe I can help with the Chinese voice translation or subtitles.

**Comment by reubenyap** [comment]
> 
> 
> Is the video going to be translated in other languages? Maybe I can help with the Chinese voice translation or subtitles.

I'll take you up on that!

**Comment by reubenyap** [comment]
I have amended this proposal to take into account the increased price of zcoin and will be considering this fully funded. Am working on this now! If anyone would like to chip in for translation work please let me know!

**Comment by raychieng** [comment]
I am interested in Chinese voice over and subtitles translation.

**Comment by raychieng** [comment]
Just wanted to know the current status of the project?

**Comment by reubenyap** [comment]
@raychieng Thanks for asking! So I'm waiting for the core upgrade and deterministic masternode to release first before we release RAP on the wallet so I decided to wait a bit on this video. Our lead dev wanted to make sure we don't release too many things on such a big infrastructure upgrade.

However RAP is already ported to the new core and is awaiting testing so we should have it pretty soon then I can work on this video (with some screens) to go with it.

Sorry for the delay!

**Pull request merged**
