### PR TITLE
Add Chinese Translation for FIRO Explorer

### PR DESCRIPTION
**Pull request by solarhell**

### CODE REVIEW

**Comment by reubenyap** [comment]
Hi @solarhell this is a great initiative would you be doing the necessary code changes?

**Comment by strahe** [comment]
@solarhell Maybe i can try

**Comment by KuroGuo** [comment]
> @solarhell Maybe i can try

You can create a new proposal

**Comment by KuroGuo** [comment]
@strahe You can create a new proposal

**Pull request closed without merging**
