### PR TITLE
Zcoin sticker pack for Telegram and Signal

### PR DESCRIPTION
**Pull request by rehrar**
What up Zcoin scrubs?

My name is Diego Salazar, also known as rehrar. I'm a contributor of the privacy cryptocurrency space, and primarily work with Monero. I also own a small design firm [Cypher Stack](https://cypherstack.com). Need more credentials? I designed both the CCS (Monero) and the ZCS that you're currently browsing, both how it works (so if you hate the flow you can blame me :P) and how it looks.

We very recently made a sticker pack for Monero. Isabella the Monero Girl, which you can view/download for [Signal](https://signal.art/addstickers/#pack_id=c7ddbbfc53c6d4a93fb9947626b8747b&pack_key=ac2999ee373b058fec9e41f1d7f6b4bc949815cc89f8868b1ab48615ca919c5f) or [Telegram](https://t.me/addstickers/MoneroGirl).

We want to make a similar sticker pack for Zcoin.

We will be open to suggestions from the community as to what the featured character should be, and make a few drafts to gather feedback. In the event one gains considerably more traction than the others, we'll move forward with that one, but if there's contention then we will either work with the Zcoin core team or I'll decide myself which is the strongest to move forward with. Trust me. I'm a designer. ;)

After the character is decided on we'll make twenty stickers for the sticker pack, covering many of the basic emojies such as smile, laugh, cry, thumbs up, thumbs down, angry, annoyed, etc. If you guys wanted more stickers perhaps this proposal can be overfunded and we'd make even more (depends on what your core team decides to do with the extra money). I can also assist in getting them on Telegram and Signal

All illustrations will be licensed CC BY 4.0. 

We'd ask for roughly $100 for character creation and $500 for the twenty stickers for a total of $600. At present Zcoin exchange rate is $6.86/XZC bringing the total to 87.5 XZC. 14.5 of which will be released upon completed character design (first milestone) and the remainder when all stickers are made.

Additional disclaimer, I would put the stickers on my portfolio site.

If you guys think this is a fun idea, then I'm game to make it happen. I'm happy to answer any questions in this MR. Keep trucking on, Zcoin!

### CODE REVIEW

**Comment by reubenyap** [comment]
I am downvoting this just because we were called scrubs ;) 

But in seriousness I think this is a fun proposal. I like Diego's work and I think we're in need for some quality stickers with meme-ability ;D

**Comment by JustSavil** [comment]
Stickers would be cool to share. We going with the Zcoin Phoenix?? :D

**Comment by rehrar** [comment]
@Krzk7 We can indeed do the phoenix, but if the community wanted something else we can do that too.

**Comment by HysMagus** [comment]
I'm down for it as long as you can stuff some inside jokes in there :)

**Comment by rehrar** [comment]
@HysMagus Sounds good! What inside jokes are you thinking?

**Comment by HysMagus** [comment]
Well it wouldn't be an inside joke if it was posted on this PR :)

Perhaps for inside jokes maybe some references to the Zcoin Meme Sticker
pack

**Comment by Chameleon-Shin** [comment]
Not necessarily onboard.. especially for the asking price

Please show example(s) of work and/or styles presented for the Zcoin sticker set – could very well help garner further support for your cause

**Comment by HysMagus** [comment]
@Chameleon-Shin Here's one of his packs from Telegram:
Isabella the Monero Girl: https://t.me/addstickers/MoneroGirl

**Comment by rehrar** [comment]
Just finished another sticker pack for Samourai Wallet. You can check that one out also https://t.me/addstickers/OnnaTheSamouraiGirl

@Chameleon-Shin if the price is too steep, I can understand, but unfortunately, living in the first world, I gotta pay the bills somehow, and each sticker is a custom illustration.

**Pull request merged**
