### PR TITLE
Japanese Community Manager

### PR DESCRIPTION
**Pull request by reubenyap**
This is to fund Japanese community manager for our Japanese group that will provide Japanese translation support in our Telegram Japan community https://t.me/zcoin_jp

This amount of 60 XZC is worth around 180 USD for one month of work and will be for the month of January 2020.

If anyone is interested in taking up this position let us know.

### CODE REVIEW

**Comment by HysMagus** [comment]
This looks great! If this gets merged in, @arcadiamediagroup is down to donate  👍

**Comment by justanwar** [comment]
LGTM

**Comment by JustSavil** [comment]
I like this idea for a proposal. Let's ship it.

**Comment by HysMagus** [comment]
+40 XZC from @arcadiamediagroup
824c1adf1e0573f39fbb9c5984ad85c57153c8c1839ec0e789ddc3816a83fa0c

**Comment by reubenyap** [comment]
This proposal is now fully funded! Will keep you posted once we have appointed and commenced the Community Management for the Japan group.

**Comment by reubenyap** [comment]
@Shujuij who was the previous CM for the group has agreed to retake this roll. First milestone has been released to him.

**Pull request merged**
