### PR TITLE
Create p2plendingxzc

### PR DESCRIPTION
**Pull request by jeedojung**
Proposal : 
Micro lending are difficult to make and there are still quite a lot of interest rates different on lender and borrower, so there are still many people who can't access the funding.
P2P lending is going to help to people make money from there asset both side to borrow money and lend money with better returns on both sides.
The p2p platform matchs borrowers and lenders by a method to assess along with Guarantees of Lender must get their return without any risk. 
The p2p platform need borrower's collateral, crypto currency like bitcoin, Zcoin, ETH eles. can be collateral. The borrower can borrow up to 90% of the credit limit depending on the assets placed and the credit of the borrower.

This platform will bring acliquidity to Satangpro exchanger 

P2P platform will be developed by Antia technology

### CODE REVIEW

**Comment by reubenyap** [comment]
Hi Jeedojung, your commit doesn't follow the formatting correctly so it doesn't appear on Ideas!

Don't put commas in the amount and follow the date format like this January 31, 2019

This is an interesting proposal however needs much more detail for example who is Antia technology, and how the p2p lending system is going to be built.

Also how does it differ from current lending platforms such as Constant P2P which support XZC?

Looking forward to see your proposal amended!

**Comment by jeedojung** [comment]
Hello Sir,

Thanks for reply me. It is very impressive that Zcoin team is interested this project.

Thx for reference Constant. I dont know Constant before but it seem like my idea almost hundred percent. 
It is just credit score and maximum loan should be added, to screen bad credit people out from platform 

low credit , they can loan less 
high credit, they can loan much

The important different thing is, it will be platform for Thai people to help them convert crypto to THB by directly using Satangpro.

All crypto asset can turn to Thai bath, then they can have more liquidity to move ecosystem bigger.

Sorry for the code, I will fix the code as ur advice.

Thx
Best regards,
Jeerapat

**Comment by reubenyap** [comment]
Could you give some background on Antia Technology's team and previous work?

**Comment by jeedojung** [comment]
Hello,

I put the link on this. Sorry for frankly speaking. I can't coding by
myself. But i would like to find someone to make it happen.

https://www.antiersolutions.com/p2p-lending-software-development/


Best regards,
Jeerapat

**Comment by reubenyap** [comment]
Ahh I noticed the site doesn't look like it's designed for crypto payments and is a whitelabel type of thing. I was under the impression this would have been lead by a software development team that you lead!

Given that ConstantP2P already exists and this is a centralized type of lending software system, probably not the best proposal.

**Comment by reubenyap** [comment]
Closing this PR for the moment until the author updates.

**Pull request closed without merging**
