### PR TITLE
Create @Nazmul465-Pakistan-Community-Management.md

### PR DESCRIPTION
**Pull request by Nazmul465**

### CODE REVIEW

**Comment by Nazmul465** [comment]
Hello sir/maam
I'am Nazmul Ahmed Joy i'am from Pakistan in my country people are starting to adopt crypto and becoming familiar with it.As a Pakistani brand ambassador I want to represent Zcoin in My country as helping to grow Zcoin in My country engaging people from my Country to Zcoin help to spread Zcoin Globally as becoming Zcoin brand ambassador

**Comment by MichaelBernhardt** [comment]
Hi Namul, what attracts you to Zcoin? Do you have experience as an ambassador?

**Comment by Nazmul465** [comment]
1st:I have been attracted to Zcoin becouse of the Zcoin sigma technology!
It's really awesome and helpful and also the community.
2nd:Yes I have exparince of managing Community such as in
ARCS,LoveChain,QUUBE exchange etc.

**Comment by Nazmul465** [comment]
Hello team,

There are many trader who want to trade in Zcoin and already trading from
India I want to help and support them to better learning and understanding
Zcoin ❤ please make your decision team 😊

**Comment by reubenyap** [comment]
Closing this due to lack of interest.

**Pull request closed without merging**
