### PR TITLE
Implement Coin Control on the Zcoin Client 

### PR DESCRIPTION
**Pull request by HysMagus**
---
layout: fr
title: Implementing Coin Control onto the Zcoin GUI Client
author: The Arcadia Group @ArcadiaMediaGroup
date: December 30, 2019
amount: 1893.33
milestones:
  - name: Initial: Integrating Zcoin-style Coin Control into the Zcoin GUI Client 
    funds: 45% (852 XZC)
    done:
    status: unfinished
  - name: Testing Period
    funds: 30% (568‬ XZC)
    done:
    status: unfinished
  - name: Acceptance and Testing
    funds: 25% (473.33‬ XZC)
    done:
    status: unfinished
payouts:
  - date:
    amount:
  - date:
    amount:

<s> amount: 2,155
milestones:
  - name: Initial: Integrating Zcoin-style Coin Control into the Zcoin GUI Client 
    funds: 45% (970 XZC)
    done:
    status: unfinished
  - name: Testing Period
    funds: 30% (647‬ XZC)
    done:
    status: unfinished
  - name: Acceptance and Testing
    funds: 25% (538‬ XZC)
    done:
    status: unfinished
payouts:
  - date:
    amount:
  - date:
    amount:
---</s>
#Proposal
Our plan is to review the current implementation of coin control on QT, and replicate it in the Client, while having our UI specialist work in tandem to create a series of sexy frontend elements for the client version of coin control.

The majority of time will be spent porting functionality from coin control in QT to the Vue JS Client 

The payout breakdown would be a 45% initial payment, followed by a 30% payout upon the release of a initial testable version and a 25% final payout upon the acceptance and completion of the project. 

The estimated timeframe on this project would be approximately two calendar weeks, which is 1 calendar (2 week) sprints.

The team breakdown for this engagement would be:

* 1 Full Time Developer 
* 1 UI/UX Specialist (.5 Sprint)
* 1 Project Manager

### CODE REVIEW

**Comment by reubenyap** [comment]
I think this is one of the few features that is missing on our current GUI client (that and BIP47) so this is pretty important.

**Comment by goodc0re** [comment]
Yes, coin control is important. I use Electrum-XZC because it offers coin control. Would be great if the Zcoin GUI would offer it, too.

**Comment by HysMagus** [comment]
Updated PR to account for the Zcoin Price Increase 😃  amount: 1893.33
milestones:
  - name: Initial: Integrating Zcoin-style Coin Control into the Zcoin GUI Client 
    funds: 45% (852 XZC)
    done:
    status: unfinished
  - name: Testing Period
    funds: 30% (568‬ XZC)
    done:
    status: unfinished
  - name: Acceptance and Testing
    funds: 25% (473.33‬ XZC)
    done:
    status: unfinished
payouts:
  - date:
    amount:
  - date:
    amount:

**Comment by HysMagus** [comment]
Repos for Watching the Work Occur:
https://github.com/ArcadiaMediaGroup/zcoin-working-repo/tree/coincontrol-clientapi
https://github.com/ArcadiaMediaGroup/zcoin-client/tree/feature/coin-control

Work should be committed to the repo tomorrow. :)

**Comment by HysMagus** [comment]
Update time! Arcadia will be releasing a testable binary shortly. It works with the binary generated from the zcoin-working-repo coin control branch. 
The requisite branches to build a binary are:
https://github.com/ArcadiaMediaGroup/zcoin-client/tree/coin-control
and 
https://github.com/ArcadiaMediaGroup/zcoin-working-repo/tree/coincontrol-clientapi

What works:

- Coin Control on Normal Transactions

What still being worked on:
- Coin Control on Sigma Transactions (we are adding a pop up to ask for the password when selecting UTXOs to mint)

Give it a compile and let us know what you think!

**Comment by reubenyap** [comment]
I have updated the proposal to include the amounts paid to Arcadia who have graciously agreed to adjust the pricing in view of the recent XZC price increase.

**Pull request merged**
