### PR TITLE
XZC Merchant Map

### PR DESCRIPTION
**Pull request by HysMagus**
---
layout: wip
title: XZC Merchant Map
author: The Arcadia Group
date: January 13, 2020
amount: 126
milestones:
  - name: Hosting Costs 
    funds: 9% (11.4 XZC)
    done:
    status: unfinished
  - name: After 6 Months of Operation (Maintainence and Support)
    funds: 91% (114.6‬ XZC)
    done:
    status: unfinished
payouts:
  - date:
    amount:
  - date:
    amount:
---
#Proposal
This is a lightweight proposal for the implementation of a zcoin merchant map using the same system that PIVX does for https://pivxplaces.com/

The functionality for this site includes:
- A Map with Locations Accepting XZC
- A Directory with Locations

This is an extremely lightweight proposal with the intention of getting something going in relation to the Zcoin Merchants concept.

### CODE REVIEW

**Comment by reubenyap** [comment]
This is something I've really wanted for a super long time and we have existing merchant lists that we want to incorporate. Getting this question a lot too, where can I use my zcoin and a site like this would be great!

**Comment by MichaelBernhardt** [comment]
126XZC seems really reasonable!

This would help with a lot with approaching new merchants to accept Zcoin because being on this map/list should be great advertising for them.

If this gets approved, I'll be contributing.

**Comment by JustSavil** [comment]
This is great and indeed would be useful for approaching future merchants and franchises. The Prompt pay integration of Zcoin was a great jump off to add millions of merchants at once if I recall. I would pitch in if this became real.

**Comment by HysMagus** [comment]
Here's a rough draft of the website, I'm still integrating the maps API key (have to grab one from a business acct) http://zcoinmerchants.com/

**Comment by reubenyap** [comment]
Due to the small amount asked for and the non contentious nature of this, am opening this for funding.

**Comment by reubenyap** [comment]
@HysMagus Could you update to the public?
Basically it's almost done but now currently populating merchants.

**Comment by HysMagus** [comment]
Will write an update tonight! 😁

**Comment by HysMagus** [comment]
Update time! So the Zcoin Merchants site has been setup with the following things:

- Site itself is now hosted on one of my dedicated servers running the AIT Themes Directory Plugin
- Current Google Maps API is now set to the Arcadia one, but we'll probably move it at a later point.
- I have approximately 6 companies drafted that will be added to the site as soon as I get some missing information/and or location
- I'm waiting on a few XZC Merchant processors to shoot me a list of companies that accept XZC. There are some consent things involved there so that may take a while.

**Comment by HysMagus** [comment]
Zcoin Merchants has been operating for 6 months, and we are running up on the date of the second milestone release (donations haven't hit the full amount needed for it). I would like to request that whatever amount has been donated for the second milestone be donated to the Lelantus Audit in lieu of it being distributed to myself. :)

**Pull request merged**
