### PR TITLE
Zcoin Africa Telegram community

### PR DESCRIPTION
**Pull request by Hola763**
Africans are adopting to crypto world, I can say more investors and partnership are in Africa, especially in Nigeria, South Africa Uganda Kenya

I will love to be a brand ambassador and local regional community builder in Africa,  in other to promote Zcoin with unique skills I possess

the most important thing is to create a community on telegram Africa and the total amount needed for the project is about 50 Zcoin for community management. 
The Expiration date is May 29, 2020

### CODE REVIEW

**Comment by MichaelBernhardt** [comment]
Hi Hola!

Have you done any work like this before? How long would 50 Zcoin cover?

**Comment by Hola763** [comment]
Yes, I have worked with several projects having cognitive knowledge about blockchain and its tech.

The 50 Zcoin would cover for a month.

**Comment by reubenyap** [comment]
Could you tell us what goals and events you would want to achieve with the Zcoin African community and where you would be populating members from? Do you have any references from previous work that you have done?

**Comment by Hola763** [comment]
Having great experience working with different blockchain project. I positioned as the brand ambassador of Scientific Coin Platform West Africa Region, ARPA, CPChain, Vid project as a moderator. 

Olayiwola Ogboye
https://www.linkedin.com/in/ogboye-olayiwola-ba95b416b

**Comment by Hola763** [comment]
I will for sure help with the right strategy that will attract investor to Zcoin
Doing reward program that will help add new members to join the community.
I will represent Zcoin both offline and online at blockchain events 
I will also organize local meet up both online and offline to bring more user to Zcoin.

**Comment by reubenyap** [comment]
Closing this due to lack of interest.

**Pull request closed without merging**
