### PR TITLE
Flare Wallet Mobile & Desktop Integration + Non-Custodial Masternode Management

### PR DESCRIPTION
**Pull request by mattt21**
layout: fr
title: Flare Wallet Mobile & Desktop Integration + Non-Custodial Masternode Management
author: The Flare Wallet Team
date: May 1st, 2020
amount: 1750 XZC
milestones:
  - name: Full Integration
    funds: 1750 XZC
    done:
    status: unfinished
payouts:
  - date:
    amount:
  - date:
    amount:
---

This proposal is for the integration of XZC into Flare Wallet Desktop & Mobile with full swap support & Mobile Masternode Management.

The XZC Masternode Management is a custom developed solution specifically for ProReg masternodes (deterministic nodes). Being able to run Znodes from Flare mobile allows for users to set their collateral in their mobile wallet, and activate their masternode as well (the actual masternode server needs to be set up individually or using a third party service).

Masternode rewards also are received directly in your wallet. This is a fully non-custodial solution, you retain your keys and privacy 100% of the time.

To read more about Flare:

https://flarewallet.io/blog

How to launch masternodes from Flare Mobile:

https://flarewallet.io/flare-update-how-to-launch-your-masternodes-in-flare-mobile

### CODE REVIEW

**Comment by HysMagus** [comment]
I like it! Having some more coverage in terms of long-term maintenance and handling of future updates as well as some of the related concepts may be a good idea. Overall concept ACK, looking forward to seeing this get funded!

**Comment by JustSavil** [comment]
This is a great idea in making masternode management more accessible while safe. I think a tool like this would make an even bigger case for further adoption of Zcoin. I hope it will be managed with updates as well.

**Comment by mattt21** [comment]
> This is a great idea in making masternode management more accessible while safe. I think a tool like this would make an even bigger case for further adoption of Zcoin. I hope it will be managed with updates as well.

Thanks for the support @HysMagus  & @Krzk7. Yes, updates will be regularly managed - once XZC is added, it is added permanently regardless of any other future forks/upgrades etc.

If you guys have any feedback to Flare (especially mobile where masternode management will be), feel free to let me know as well. Love to hear from the community on feedback.

**Comment by justanwar** [comment]
What kind of key export is available? Mnemonics or private keys?

**Comment by mattt21** [comment]
@justanwar 12 word mnemonic phrase, uses standard bip 44 path derivation. Depending on the zcoin core derivation process, it could be compatible. Have not checked myself though.

**Pull request merged**
